name: Tests

on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  unity_tests:
    name: Unity Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Main Cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run Tests
        id: testStep
        uses: game-ci/unity-test-runner@v2
        with:
          projectPath: Foni
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Store Test Result
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: ${{ steps.testStep.outputs.artifactsPath }}

      - name: Store Code Coverage
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results
          path: ${{ steps.testStep.outputs.coveragePath }}
